Do not call `_handle_moe_modules()`, otherwise it will cause AttributeError: 'Qwen3_5MoeExperts' object has no attribute 'down_proj'
Signed-off-by: ZX-ModelCloud <zx@modelcloud.ai>