Refractor (#12)
* rename

* rename is_custom_model => is_model_patchable. it has nothing to do with custom model but if we have this model registered for patching

* rename

* set default

* use weakref for tracker

* add test

* refractor away LazyImport

* fix missing file

* add to_meta() and use it

* comment

* added test_qwen3_5_moe()

Signed-off-by: ZX-ModelCloud <zx@modelcloud.ai>

* Do not call `_handle_moe_modules()`, otherwise it will cause AttributeError: 'Qwen3_5MoeExperts' object has no attribute 'down_proj'

Signed-off-by: ZX-ModelCloud <zx@modelcloud.ai>

* fix function name

Signed-off-by: ZX-ModelCloud <zx@modelcloud.ai>

* logbar has no .trace api (we should add an alias for it)

* format

* lazy import

* format import

* format

* unit test to only convert 1 layer for speedup

---------

Signed-off-by: ZX-ModelCloud <zx@modelcloud.ai>
Co-authored-by: ZX-ModelCloud <zx@modelcloud.ai>